name: Docker Image CI

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: DockerHub

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: tjmehta/apple_tv_now_playing:${{ steps.get_version.outputs.VERSION }}
          cache-from: type=gha,src=/tmp/.buildx-cache
          cache-to: type=gha,dest=/tmp/.buildx-cache-new

      - name: Move cache
        run: |
          if [ -d "/tmp/.buildx-cache" ]; then
            echo "Removing old cache directory"
            rm -rf /tmp/.buildx-cache
          else
            echo "No old cache directory found"
          fi

          if [ -d "/tmp/.buildx-cache-new" ]; then
            echo "Moving new cache directory"
            mv /tmp/.buildx-cache-new /tmp/.buildx-cache
          else
            echo "No new cache directory found"
          fi

          echo "Cache operation completed"
